services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    environment:
      - DB_URL="postgres://postgres:Quockhanh208@@postgres/backend_template?sslmode=disable"
    env_file:
      - .env
    networks:
      - app-network
  postgres:
    image: postgres:16.9-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Quockhanh208@
      - POSTGRES_DB=backend_template
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d backend_template"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
volumes:
  redis_data:
  postgres_data:
networks:
  app-network:
    driver: bridge